import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

// Função para identificar se um medicamento é psicotrópico ou controlado
// (Baseado em uma lista simplificada de algumas substâncias controladas comuns)
const isPsicotropico = (principioAtivo: string) => {
  const controlados = [
    'ALPRAZOLAM',
    'AMITRIPTILINA',
    'BACLOFENO',
    'BIPERIDENO',
    'BROMAZEPAM',
    'BUPROPIONA',
    'CARBAMAZEPINA',
    'CARBONATO DE LÍTIO',
    'CLOMIPRAMINA',
    'CLONAZEPAM',
    'CLORPROMAZINA',
    'DESVENLAFAXINA',
    'DIAZEPAM',
    'DULOXETINA',
    'ESCITALOPRAM',
    'FENOBARBITAL',
    'FENTANILA',
    'FLUNITRAZEPAM',
    'FLUOXETINA',
    'HALOPERIDOL',
    'IMIPRAMINA',
    'LEVOMEPROMAZINA',
    'LORAZEPAM',
    'MIDAZOLAM',
    'MORFINA',
    'NALTREXONA',
    'NITRAZEPAM',
    'NORTRIPTILINA',
    'OXCARBAZEPINA',
    'PERICIAZINA',
    'PETIDINA',
    'PREGABALINA',
    'PROMETAZINA',
    'SERTRALINA',
    'TIORIDAZINA',
    'TRAMADOL',
    'VENLAFAXINA',
    'ÁCIDO VALPRÓICO',
  ];

  const ativoUpper = principioAtivo.toUpperCase();
  return controlados.some(substancia => ativoUpper.includes(substancia));
};

// Função para tentar extrair a concentração e forma farmacêutica
const parseMedicamento = (principioAtivo: string) => {
  // Regex para encontrar a concentração (ex: 10 MG/ML, 500 MG, 100 UI/ML, 2 % + 1:80.000)
  const concentracaoMatch = principioAtivo.match(/([\d\.\,\:\s\+]+(?:MG\/ML|MG|UI\/ML|UI|%|G|G\/ML|MCG|MG\/\s?\+\s?UI|UI\/\s?\+\s?UI))(\s|\/)/i);
  let concentracao = concentracaoMatch ? concentracaoMatch[1].trim() : 'N/A';

  // Tentativa de limpar a concentração, removendo espaços indesejados e tratando '+'
  concentracao = concentracao.replace(/\s+/g, ' ').replace(/\s?\+\s?/g, ' + ').trim();

  // Mapeamento simples de palavras-chave para formas farmacêuticas
 const formaFarmaceuticaMap: { [key: string]: string } = {
    'XAROPE': 'Xarope',
    'COMPRIMIDO DE LIBERAÇÃO PROLONGADA': 'Comprimido de Liberação Prolongada',
    'COMPRIMIDO DE LIBERAÇÃO CONTROLADA': 'Comprimido de Liberação Controlada',
    'COMPRIMIDO SUBLINGUAL': 'Comprimido Sublingual',
    'COMPRIMIDO MASTIGÁVEL': 'Comprimido Mastigável',
    'COMPRIMIDO': 'Comprimido',
    'CÁPSULA DURA DE LIBERAÇÃO PROLONGADA': 'Cápsula de Liberação Prolongada',
    'CÁPSULA': 'Cápsula',
    'SOLUÇÃO INJETÁVEL': 'Solução Injetável',
    'SUSPENSÃO INJETÁVEL': 'Suspensão Injetável',
    'PÓ PARA SOLUÇÃO INJETÁVEL': 'Pó para Solução Injetável',
    'SOLUÇÃO ORAL': 'Solução Oral',
    'SUSPENSÃO ORAL': 'Suspensão Oral',
    'CREME VAGINAL': 'Creme Vaginal',
    'POMADA': 'Pomada',
    'CREME': 'Creme',
    'GEL': 'Gel',
    'AEROSSOL': 'Aerossol',
    'XAMPU': 'Xampu',
    'PASTILHA': 'Pastilha',
    'GOMA DE MASCAR': 'Goma de Mascar',
    'ADESIVO TRANSDÉRMICO': 'Adesivo Transdérmico',
    'LOÇÃO': 'Loção',
    'DRÁGEA': 'Drágea',
    'ELIXIR': 'Elixir',
    'SOLUÇÃO TÓPICA': 'Solução Tópica',
    'SOLUÇÃO OTOLÓGICA': 'Solução Otológica',
    'SOLUÇÃO PARA INALAÇÃO': 'Solução para Inalação',
    'SOLUÇÃO OFTÁLMICA': 'Solução Oftálmica',
  };

  let formaFarmaceutica = 'Outra';
  const ativoUpper = principioAtivo.toUpperCase();

  for (const key in formaFarmaceuticaMap) {
    if (ativoUpper.includes(key)) {
      formaFarmaceutica = formaFarmaceuticaMap[key];
      break;
    }
  }

  return { concentracao, formaFarmaceutica };
};

const listaDePrincipiosAtivos = [
  // Lista de 362 medicamentos fornecida pelo usuário
  'ACEBROFILINA 10 MG/ML XAROPE FRASCO 120 ML', 'ACEBROFILINA 5 MG/ML XAROPE FRASCO 120 ML', 'ACICLOVIR 200 MG COMPRIMIDO', 'ACICLOVIR 5 % CREME BISNAGA 10 G', 'ÁCIDO ACETILSALICÍLICO 100 MG COMPRIMIDO', 'ÁCIDO ASCÓRBICO 100 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 5 ML', 'ÁCIDO ASCÓRBICO 200 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'ÁCIDO ASCÓRBICO 200 MG/ML SOLUÇÃO ORAL FRASCO 30 ML', 'ÁCIDO FÓLICO 5 MG COMPRIMIDO', 'ÁCIDO TIÓCTICO 600 MG COMPRIMIDO', 'ÁCIDO TRANEXÂMICO 50 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 5 ML', 'ÁCIDO VALPRÓICO (VALPROATO DE SÓDIO) 250 MG CÁPSULA', 'ÁCIDO VALPRÓICO (VALPROATO DE SÓDIO) 250 MG COMPRIMIDO', 'ÁCIDO VALPRÓICO (VALPROATO DE SÓDIO) 300 MG COMPRIMIDO DE LIBERAÇÃO PROLONGADA', 'ÁCIDO VALPRÓICO (VALPROATO DE SÓDIO) 50 MG/ML XAROPE FRASCO 100 ML', 'ÁCIDO VALPRÓICO (VALPROATO DE SÓDIO) 500 MG COMPRIMIDO COMPRIMIDO', 'ÁCIDO VALPRÓICO (VALPROATO DE SÓDIO) 500 MG COMPRIMIDO DE LIBERAÇÃO PROLONGADA', 'ÁCIDOS GRAXOS ESSENCIAIS SOLUÇÃO FRASCO 100 ML', 'ADENOSINA, FOSFATO 3 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'AESCULUS HIPPOCASTANUM L. (CASTANHA DA ÍNDIA) 100 MG CÁPSULA', 'ÁGUA DESTILADA SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'ÁGUA DESTILADA SOLUÇÃO INJETÁVEL AMPOLA 5 ML', 'ALBENDAZOL 40 MG/ML SUSPENSÃO ORAL FRASCO 10 ML', 'ALBENDAZOL 400 MG COMPRIMIDO MASTIGÁVEL', 'ALENDRONATO DE SÓDIO 70 MG COMPRIMIDO', 'ALOPURINOL 100 MG COMPRIMIDO', 'ALOPURINOL 300 MG COMPRIMIDO', 'ALPRAZOLAM 0,25 MG COMPRIMIDO', 'ALPRAZOLAM 0,5 MG COMPRIMIDO', 'ALPRAZOLAM 1 MG COMPRIMIDO', 'ALPRAZOLAM 2 MG COMPRIMIDO', 'ALTEPLASE 50 MG PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA', 'AMANTADINA 100 MG COMPRIMIDO', 'AMBROXOL, CLORIDRATO 3 MG/ML XAROPE FRASCO 100 ML', 'AMBROXOL, CLORIDRATO 6 MG/ML XAROPE FRASCO 100 ML', 'AMICACINA, SULFATO 250 MG/ ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'AMINOFILINA 24 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'AMIODARONA, CLORIDRATO 200 MG COMPRIMIDO', 'AMITRIPTILINA, CLORIDRATO 25 MG COMPRIMIDO', 'AMOXICILINA + CLAVULANATO DE POTÁSSIO 50 MG + 12,5 MG/ ML SUSPENSÃO ORAL FRASCO 75 ML', 'AMOXICILINA + CLAVULANATO DE POTÁSSIO 500 MG + 125 MG COMPRIMIDO', 'AMOXICILINA 50 MG/ML PÓ PARA SUSPENSÃO FRASCO 150 ML', 'AMOXICILINA 50 MG/ML PÓ PARA SUSPENSÃO FRASCO 60 ML', 'AMOXICILINA 500 MG CÁPSULA', 'AMPICILINA 500 MG CÁPSULA', 'ANLODIPINO, BESILATO 5 MG COMPRIMIDO', 'APIXABANA 5 MG COMP COMPRIMIDO', 'ATENOLOL 25 MG COMPRIMIDO', 'ATENOLOL 50 MG COMPRIMIDO', 'ATROPINA, SULFATO 0,25 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'ATROPINA, SULFATO 0,5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'AZITROMICINA 40 MG/ML PÓ PARA SUSPENSÃO FRASCO 600 MG', 'AZITROMICINA 500 MG COMPRIMIDO', 'BACLOFENO 10 MG COMPRIMIDO', 'BACLOFENO 20 MG COMPRIMIDO', 'BENZILPENICILINA BENZATINA 1.200.000 UI PÓ PARA SUSPENSÃO INJETÁVEL FRASCO- AMPOLA', 'BENZILPENICILINA BENZATINA 600.000 UI PÓ PARA SUSPENSÃO INJETÁVEL FRASCO- AMPOLA', 'BENZILPENICILINA PROCAÍNA + BENZILPENICILINA POTÁSSICA 400.000 UI PÓ PARA SUSPENSÃO INJETÁVEL FRASCO- AMPOLA', 'BETAMETASONA, DIPROPIONATO + BETAMETASONA, FOSFATO DISSÓDICO 5 + 2 MG/ML SUSPENSÃO INJETÁVEL AMPOLA 1 ML', 'BICARBONATO DE SÓDIO 8,4 % SOLUÇÃO INJETÁVEL FRASCO 250 ML', 'BICARBONATO DE SÓDIO 8,4 % SOLUÇÃO INJETÁVEL FRASCO- AMPOLA 10 ML', 'BIPERIDENO, CLORIDRATO 2 MG COMPRIMIDO', 'BIPERIDENO, LACTATO 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'BROMAZEPAM 3 MG COMPRIMIDO', 'BROMOPRIDA 10 MG CÁPSULA', 'BROMOPRIDA 10 MG COMPRIMIDO', 'BROMOPRIDA 4 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'BROMOPRIDA 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'BUPROPIONA, CLORIDRATO 150 MG COMPRIMIDO DE LIBERAÇÃO CONTROLADA', 'CAPTOPRIL 25 MG COMPRIMIDO', 'CAPTOPRIL 50 MG COMPRIMIDO', 'CARBAMAZEPINA 20 MG/ML SUSPENSÃO ORAL FRASCO 100 ML', 'CARBAMAZEPINA 200 MG COMPRIMIDO', 'CARBAMAZEPINA 400 MG COMPRIMIDO', 'CARBAMIDA 100 MG/ML SOLUÇÃO OTOLÓGICA FRASCO 10 ML', 'CARBONATO DE CÁLCIO + COLECALCIFEROL 500 MG + 400 UI COMPRIMIDO', 'CARBONATO DE LÍTIO 300 MG COMPRIMIDO', 'CARVÃO VEGETAL ATIVADO PÓ ENVELOPE 50 G', 'CARVÃO VEGETAL ATIVADO PÓ POTE 250 G', 'CARVEDILOL 12,5 MG COMPRIMIDO', 'CARVEDILOL 25 MG COMPRIMIDO', 'CARVEDILOL 3,125 MG COMPRIMIDO', 'CARVEDILOL 6,25 MG COMPRIMIDO', 'CEFALEXINA 50 MG/ML SUSPENSÃO ORAL FRASCO 100 ML', 'CEFALEXINA 500 MG CÁPSULA', 'CEFALEXINA 500 MG COMPRIMIDO', 'CEFTRIAXONA SÓDICA 1 G PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA IM', 'CEFTRIAXONA SÓDICA 1 G PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA IV', 'CETOCONAZOL 2 % XAMPU FRASCO 100 ML', 'CETOCONAZOL 200 MG COMPRIMIDO', 'CETOPROFENO 100 MG PÓ PARA SUSPENSÃO INJETÁVEL FRASCO- AMPOLA', 'CETOPROFENO 50 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'CILOSTAZOL 50 MG COMPRIMIDO', 'CIMETIDINA 150 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'CIMETIDINA 200 MG COMPRIMIDO', 'CINARIZINA 25 MG COMPRIMIDO', 'CIPROFLOXACINO, CLORIDRATO 2 MG/ML SOLUÇÃO INJETÁVEL FRASCO 100 ML', 'CIPROFLOXACINO, CLORIDRATO 500 MG COMPRIMIDO', 'CLARITROMICINA 500 MG COMPRIMIDO', 'CLINDAMICINA, CLORIDRATO 300 MG CÁPSULA', 'CLOMIPRAMINA, CLORIDRATO 25 MG COMPRIMIDO', 'CLONAZEPAM 0,5 MG COMPRIMIDO', 'CLONAZEPAM 2 MG COMPRIMIDO', 'CLONAZEPAM 2,5 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'CLONIDINA, CLORIDRATO 0,1 MG COMPRIMIDO', 'CLOPIDOGREL, BISSULFATO 75 MG COMPRIMIDO', 'CLORETO DE BENZALCÔNIO + CLORETO DE SÓDIO 0,1 + 9 MG/ML SOLUÇÃO NASAL FRASCO 30 ML', 'CLORETO DE POTÁSSIO 10 % SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'CLORETO DE POTÁSSIO 19,10 % SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'CLORETO DE SÓDIO 0,9 % SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'CLORETO DE SÓDIO 20 % SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'CLORPROMAZINA, CLORIDRATO 100 MG COMPRIMIDO', 'CLORPROMAZINA, CLORIDRATO 25 MG COMPRIMIDO', 'CLORPROMAZINA, CLORIDRATO 40 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'CLORPROMAZINA, CLORIDRATO 5 MG/ML SOLUÇÃO INJETÁVEL FRASCO- AMPOLA 5 ML', 'CLOTRIMAZOL 10 MG/G CREME BISNAGA 20 G', 'COLAGENASE + CLORANFENICOL 0,6 UI + 10 MG/G POMADA BISNAGA 30 G', 'CUMARINA + TROXERRUTINA 15 + 90 MG DRÁGEA', 'DABIGATRANA, ETEXILATO 110 MG CÁPSULA CÁPSULA', 'DABIGATRANA, ETEXILATO 150 MG CÁPSULA CÁPSULA', 'DAPAGLIFLOZINA 10 MG COMPRIMIDO DE LIBERAÇÃO CONTROLADA', 'DELTAMETRINA 0,2 MG/ML XAMPU FRASCO 100 ML', 'DESVENLAFAXINA, SUCCINATO MONOIDRATADO 100 MG COMPRIMIDO DE LIBERAÇÃO PROLONGADA', 'DESVENLAFAXINA, SUCCINATO MONOIDRATADO 50 MG COMPRIMIDO', 'DEXAMETASONA 0,1 % CREME BISNAGA 10 G', 'DEXAMETASONA 0,1 MG/ML ELIXIR FRASCO 120 ML', 'DEXAMETASONA 4 MG COMPRIMIDO', 'DEXAMETASONA, FOSFATO DISSÓDICO 2 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'DEXAMETASONA, FOSFATO DISSÓDICO 4 MG/ML SOLUÇÃO INJETÁVEL FRASCO- AMPOLA 2,5 ML', 'DEXCLORFENIRAMINA, MALEATO 0,4 MG/ML SOLUÇÃO ORAL FRASCO 100 ML', 'DEXCLORFENIRAMINA, MALEATO 0,4 MG/ML SOLUÇÃO ORAL FRASCO 120 ML', 'DEXCLORFENIRAMINA, MALEATO 2 MG COMPRIMIDO', 'DEXTRANA 70 + HIPROMELOSE + GLICEROL 1 + 3 + 2 MG/ML SOLUÇÃO OFTÁLMICA FRASCO 15 ML', 'DIAZEPAM 10 MG COMPRIMIDO', 'DIAZEPAM 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'DICLOFENACO SÓDICO 25 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 3 ML', 'DICLOFENACO SÓDICO 50 MG COMPRIMIDO', 'DIGOXINA 0,25 MG COMPRIMIDO', 'DIMENIDRINATO + PIRIDOXINA + GLICOSE + FRUTOSE 3 + 5 + 100 + 100 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'DIMENIDRINATO + PIRIDOXINA 25 + 5 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'DIOSMINA + HESPERIDINA 450 + 50 MG COMPRIMIDO', 'DIPIRONA + CAFEÍNA + ORFENADRINA 300 + 50 + 35 MG COMPRIMIDO', 'DIPIRONA + PROMETAZINA + ADIFENINA 500 + 5 + 10 MG COMPRIMIDO', 'DIPIRONA SÓDICA 500 MG COMPRIMIDO', 'DIPIRONA SÓDICA 500 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'DIPIRONA SÓDICA 500 MG/ML SOLUÇÃO ORAL FRASCO 10 ML', 'DIPIRONA SÓDICA 500 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'DOBUTAMINA, CLORIDRATO 12,5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 20 ML', 'DOXAZOSINA, MESILATO 4 MG COMPRIMIDO', 'DOXICICLINA 100 MG COMPRIMIDO', 'DULOXETINA, CLORIDRATO 30 MG COMPRIMIDO', 'DULOXETINA, CLORIDRATO 60 MG CÁPSULA', 'ENALAPRIL, MALEATO 10 MG COMPRIMIDO', 'ENALAPRIL, MALEATO 20 MG COMPRIMIDO', 'ENALAPRIL, MALEATO 5 MG COMPRIMIDO', 'ENOXAPARINA SÓDICA 40 MG SOLUÇÃO INJETÁVEL SERINGA 0,4 ML', 'EPINEFRINA 1 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'ESCITALOPRAM, OXALATO 10 MG COMPRIMIDO', 'ESCITALOPRAM, OXALATO 15 MG COMPRIMIDO', 'ESCITALOPRAM, OXALATO 20 MG COMPRIMIDO', 'ESCOPOLAMINA, BUTILBROMETO + DIPIRONA SÓDICA 4 + 500 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 5 ML', 'ESCOPOLAMINA, BUTILBROMETO 10 MG COMPRIMIDO', 'ESCOPOLAMINA, BUTILBROMETO 10 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'ESCOPOLAMINA, BUTILBROMETO 20 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'ESPIRONOLACTONA 25 MG COMPRIMIDO', 'ESTRIOL 1 MG/G CREME VAGINAL BISNAGA 50 G', 'FENITOÍNA SÓDICA 100 MG COMPRIMIDO', 'FENITOÍNA SÓDICA 50 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 5 ML', 'FENOBARBITAL 100 MG COMPRIMIDO', 'FENOBARBITAL 100 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'FENOBARBITAL 40 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'FENTANILA, CITRATO 0,05 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'FINASTERIDA 5 MG COMPRIMIDO', 'FITOMENADIONA 10 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML IM', 'FLUCONAZOL 150 MG CÁPSULA', 'FLUMAZENIL 0,1 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 5 ML', 'FLUNARIZINA, DICLORIDRATO 10 MG COMPRIMIDO', 'FLUNITRAZEPAM 1 MG COMPRIMIDO', 'FLUOXETINA, CLORIDRATO 20 MG CÁPSULA', 'FUROSEMIDA 10 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'FUROSEMIDA 40 MG COMPRIMIDO COMPRIMIDO', 'GLICLAZIDA 30 MG COMPRIMIDO DE LIBERAÇÃO PROLONGADA', 'GLICLAZIDA 60 MG COMPRIMIDO DE LIBERAÇÃO PROLONGADA', 'GLICONATO DE CÁLCIO 10 % SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'GLICOSAMINA, SULFATO + CONDROITINA, SULFATO 500 + 400 MG CÁPSULA CÁPSULA', 'GLICOSE 25 % SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'GLICOSE 50 % SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'HALOPERIDOL 1 MG COMPRIMIDO', 'HALOPERIDOL 2 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'HALOPERIDOL 2 MG/ML SOLUÇÃO ORAL FRASCO 30 ML', 'HALOPERIDOL 5 MG COMPRIMIDO', 'HALOPERIDOL 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'HALOPERIDOL, DECANOATO 70 MG + 50 MG 50 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'HIDRALAZINA, CLORIDRATO 20 MG/ML SOLUÇÃO INJETÁVEL AMPOLA', 'HIDRALAZINA, CLORIDRATO 25 MG DRÁGEA', 'HIDROCORTISONA, SUCCINATO SÓDICO 100 MG PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA', 'HIDROCORTISONA, SUCCINATO SÓDICO 500 MG PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA', 'HIDRÓXIDO DE ALUMÍNIO 60 MG/ML SOLUÇÃO ORAL FRASCO 100 ML', 'HIDRÓXIDO DE ALUMÍNIO 60 MG/ML SUSPENSÃO ORAL FRASCO 150 ML', 'IBUPROFENO 100 MG/ML SUSPENSÃO ORAL FRASCO 20 ML', 'IBUPROFENO 300 MG COMPRIMIDO', 'IBUPROFENO 50 MG/ML SUSPENSÃO ORAL FRASCO 30 ML', 'IMIPRAMINA, CLORIDRATO 25 MG COMPRIMIDO', 'INSULINA GLARGINA 100 UI/ML SOLUÇÃO INJETÁVEL CARPULE 3 ML', 'INSULINA GLARGINA 100 UI/ML SOLUÇÃO INJETÁVEL FRASCO- AMPOLA 10 ML', 'INSULINA GLARGINA 100 UI/ML SOLUÇÃO INJETÁVEL UNIDADE 3 ML COM SISTEMA DE APLICAÇÃO', 'INSULINA HUMANA NPH 100 UI/ML SUSPENSÃO INJETÁVEL CARPULE 3 ML', 'INSULINA HUMANA NPH 100 UI/ML SUSPENSÃO INJETÁVEL FRASCO- AMPOLA 10 ML', 'INSULINA HUMANA REGULAR 100 UI/ML SOLUÇÃO INJETÁVEL CARPULE 3 ML', 'INSULINA HUMANA REGULAR 100 UI/ML SOLUÇÃO INJETÁVEL FRASCO- AMPOLA 10 ML', 'IPRATRÓPIO, BROMETO 0,25 MG/ML SOLUÇÃO PARA INALAÇÃO FRASCO 20 ML', 'ISOSSORBIDA, DINITRATO 5 MG COMPRIMIDO SUBLINGUAL', 'ISOSSORBIDA, MONONITRATO 20 MG COMPRIMIDO', 'ITRACONAZOL 100 MG CÁPSULA', 'LACTULOSE 667 MG/ML XAROPE FRASCO 120 ML', 'LEVODOPA + BENSERAZIDA 200 + 50 MG COMPRIMIDO', 'LEVOMEPROMAZINA, CLORIDRATO 40 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'LEVOMEPROMAZINA, MALEATO 100 MG COMPRIMIDO', 'LEVOMEPROMAZINA, MALEATO 25 MG COMPRIMIDO', 'LEVOMEPROMAZINA, MALEATO 40 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'LEVONORGESTREL + ETINILESTRADIOL 0,15 + 0,03 MG CARTELA', 'LEVONORGESTREL 0,75 MG CARTELA', 'LEVOTIROXINA SÓDICA 100 MCG COMPRIMIDO', 'LEVOTIROXINA SÓDICA 25 MCG COMPRIMIDO', 'LEVOTIROXINA SÓDICA 50 MCG COMPRIMIDO', 'LEVOTIROXINA SÓDICA 75 MCG COMPRIMIDO', 'LIDOCAÍNA, CLORIDRATO + EPINEFRINA 10 MG/ML + 1.200.000 UI SOLUÇÃO INJETÁVEL FRASCO 20 ML', 'LIDOCAÍNA, CLORIDRATO + EPINEFRINA 2 % + 1:80.000 SOLUÇÃO INJETÁVEL FRASCO- AMPOLA 20 ML', 'LIDOCAÍNA, CLORIDRATO + EPINEFRINA 20 MG/ML + 1:200.000 UI SOLUÇÃO INJETÁVEL AMPOLA 20 ML', 'LIDOCAÍNA, CLORIDRATO 100 MG/ML SOLUÇÃO TÓPICA FRASCO 50 ML', 'LIDOCAÍNA, CLORIDRATO 20 MG/G GEL BISNAGA 30 G', 'LIDOCAÍNA, CLORIDRATO 20 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 20 ML', 'LORATADINA 1 MG/ML XAROPE FRASCO 100 ML', 'LORATADINA 10 MG COMPRIMIDO', 'LORAZEPAM 2 MG COMPRIMIDO', 'LOSARTANA POTÁSSICA 50 MG COMPRIMIDO', 'MAGNÉSIO, SULFATO 10 % SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'MEBENDAZOL 100 MG COMPRIMIDO', 'MEBENDAZOL 20 MG/ML SUSPENSÃO ORAL FRASCO 30 ML', 'MEDROXIPROGESTERONA, ACETATO + ESTRADIOL, CIPIONATO 25 MG + 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 0,05 ML', 'MEDROXIPROGESTERONA, ACETATO 150 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'METILDOPA 250 MG COMPRIMIDO', 'METILDOPA 500 MG COMPRIMIDO', 'METILPREDNISOLONA, SUCCINATO 125 MG PÓ LIOFILIZADO PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA', 'METOCLOPRAMIDA, CLORIDRATO 10 MG COMPRIMIDO', 'METOCLOPRAMIDA, CLORIDRATO 4 MG/ML SOLUÇÃO ORAL FRASCO 10 ML', 'METOCLOPRAMIDA, CLORIDRATO 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'METOPROLOL, SUCCINATO 25 MG COMPRIMIDO DE LIBERAÇÃO PROLONGADA', 'METOPROLOL, SUCCINATO 50 MG COMPRIMIDO DE LIBERAÇÃO PROLONGADA', 'METRONIDAZOL (BENZOILMETRONIDAZOL) 40 MG/ML SUSPENSÃO ORAL FRASCO 100 ML', 'METRONIDAZOL 100 MG/G GEL BISNAGA 50 G', 'METRONIDAZOL 250 MG COMPRIMIDO', 'METRONIDAZOL 5 MG/ML SOLUÇÃO INJETÁVEL FRASCO 100 ML', 'MICONAZOL, NITRATO 2 % CREME VAGINAL BISNAGA 80 G', 'MIDAZOLAM, CLORIDRATO 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 3 ML', 'MORFINA, SULFATO 10 MG COMPRIMIDO', 'MORFINA, SULFATO 10 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'MORFINA, SULFATO 30 MG COMPRIMIDO', 'MORFINA, SULFATO 30 MG COMPRIMIDO DE LIBERAÇÃO CONTROLADA', 'MULTIVITAMINAS (A, B2, C, B6, B5, E) SOLUÇÃO ORAL FRASCO 20 ML', 'MULTIVITAMINAS (A, C, D, COMPLEXO B) SOLUÇÃO ORAL FRASCO 20 ML', 'MULTIVITAMINAS (A, C, D, COMPLEXO B) SOLUÇÃO ORAL FRASCO 30 ML', 'MULTIVITAMINAS (A, C, D, E, COMPLEXO B) SOLUÇÃO ORAL FRASCO 20 ML', 'MULTIVITAMINAS + SAIS MINERAIS COMPRIMIDO', 'MULTIVITAMINAS + SAIS MINERAIS COMPRIMIDO EFERVESCENTE', 'MULTIVITAMINAS + SAIS MINERAIS DRÁGEA', 'MULTIVITAMINAS + SAIS MINERAIS SUSPENSÃO ORAL FRASCO 100 ML', 'MULTIVITAMINAS B2, B6, B12, C, NICOTINAMIDA E FRUTOSE SOLUÇÃO ORAL FRASCO 150 ML', 'MULTIVITAMINAS COMPLEXO B, A, C, D3, E, K1; ASSOCIADAS COM SAIS MINERAIS ZN, SE, NA + COENZIMA Q10 COMPRIMIDO MASTIGÁVEL COMPRIMIDO', 'MULTIVITAMINAS(A, B1, B2, B5, B6, B12, PP, H, C, D, E); ASSOCIADAS COM SAIS MINERAIS (CA, FE, P, MG, MN, CU, ZN, MO, B) COMPRIMIDO FRASCO', 'NALOXONA, CLORIDRATO 0,4 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'NALTREXONA 50 MG COMPRIMIDO', 'NEOMICINA + BACITRACINA 5 + 250 MG + UI/G POMADA BISNAGA 10 G', 'NICOTINA 14 MG ADESIVO TRANSDÉRMICO UNIDADE', 'NICOTINA 2 MG GOMA DE MASCAR TABLETE', 'NICOTINA 2 MG PASTILHA PASTILHA', 'NICOTINA 21 MG ADESIVO TRANSDÉRMICO UNIDADE', 'NICOTINA 4 MG GOMA DE MASCAR TABLETE', 'NICOTINA 4 MG PASTILHA PASTILHA', 'NICOTINA 7 MG ADESIVO TRANSDÉRMICO UNIDADE', 'NIFEDIPINO 20 MG COMPRIMIDO COMPRIMIDO', 'NIMESULIDA 100 MG COMPRIMIDO', 'NIMESULIDA 50 MG/ML SOLUÇÃO ORAL FRASCO 15 ML', 'NISTATINA 100.000 UI/ML SUSPENSÃO ORAL FRASCO 50 ML', 'NISTATINA 25.000 UI/G CREME VAGINAL BISNAGA 50 G', 'NISTATINA 25.000 UI/G CREME VAGINAL BISNAGA 60 G', 'NITRAZEPAM 5 MG COMPRIMIDO', 'NITROFURANTOÍNA 100 MG CÁPSULA', 'NITROGLICERINA 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 10 ML', 'NITROGLICERINA 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 5 ML', 'NITROPRUSSETO DE SÓDIO 50 MG PÓ LIOFILIZADO PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA 2 ML', 'NOREPINEFRINA 2 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 4 ML', 'NORETISTERONA 0,35 MG COMPRIMIDO CARTELA', 'NORETISTERONA, ENANTATO DE + ESTRADIOL, VALERATO DE 50 + 5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'NORFLOXACINO 400 MG COMPRIMIDO', 'NORTRIPTILINA, CLORIDRATO 25 MG CÁPSULA', 'ÓLEO MINERAL (VASELINA LÍQUIDA / PETROLATO) SOLUÇÃO ORAL FRASCO 100 ML', 'OMEPRAZOL 20 MG CÁPSULA', 'OMEPRAZOL 40 MG PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA', 'OSELTAMIVIR, FOSFATO 75 MG CÁPSULA', 'OXCARBAZEPINA 300 MG COMPRIMIDO', 'OXCARBAZEPINA 6 % SUSPENSÃO ORAL FRASCO 100 ML', 'OXCARBAZEPINA 600 MG COMPRIMIDO', 'ÓXIDO DE ZINCO + COLECALCIFEROL + RETINOL 150 + 5000 + 900 MG + UI + UI/G POMADA BISNAGA 45 G', 'PARACETAMOL 200 MG/ML SOLUÇÃO ORAL FRASCO 10 ML', 'PARACETAMOL 200 MG/ML SOLUÇÃO ORAL FRASCO 15 ML', 'PARACETAMOL 500 MG COMPRIMIDO', 'PERICIAZINA 10 MG/ML SOLUÇÃO ORAL FRASCO 20 ML', 'PERICIAZINA 4 % SOLUÇÃO ORAL FRASCO 20 ML', 'PERMANGANATO DE POTÁSSIO 100 MG COMPRIMIDO', 'PERMETRINA 50 MG/ML LOÇÃO FRASCO 60 ML', 'PETIDINA 50 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'PREDNISOLONA 3 MG/ML SOLUÇÃO ORAL FRASCO 60 ML', 'PREDNISONA 20 MG COMPRIMIDO', 'PREDNISONA 5 MG COMPRIMIDO', 'PREGABALINA 75 MG CÁPSULA', 'PROMETAZINA, CLORIDRATO 25 MG COMPRIMIDO', 'PROMETAZINA, CLORIDRATO 25 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 2 ML', 'PROPAFENONA, CLORIDRATO 300 MG COMPRIMIDO', 'PROPÁTILNITRATO 10 MG COMPRIMIDO', 'PROPRANOLOL, CLORIDRATO 40 MG COMPRIMIDO', 'RETINOL + COLECALCIFEROL + ACETATO DE TOCOFEROL + ÁCIDO ASCORBICO + TIAMINA + RIBOFLAVINA + NICOTINAMIDA + CLORIDRATO DE PIRIDOXINA + ÁCIDO FOLICO + CIANOCOBALAMINA + FERRO + ZINCO + CÁLCIO 2664 + 400 + 10 UI + 70 + 3 + 3,4 + 17 + 4 + 0,6 MG + 2,2 MCG + 30 + 15 + 125 MG CÁPSULA', 'RETINOL + COLECALCIFEROL 50.000 + 10.000 UI SOLUÇÃO ORAL FRASCO 10 ML', 'RIVAROXABANA 10 MG COMPRIMIDO', 'RIVAROXABANA 15 MG COMPRIMIDO', 'RIVAROXABANA 20 MG COMPRIMIDO', 'ROCURÔNIO, BROMETO 10 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 5 ML', 'SAIS PARA REIDRATAÇÃO ORAL (NACL 3,5 G + GLICOSE 20 G + CITRATO NA 2,9 G + KCL 1,5 G) 27,9 G PÓ PARA SOLUÇÃO ENVELOPE', 'SALBUTAMOL, SULFATO 100 MCG/DOSE AEROSSOL FRASCO 200 DOSES', 'SECNIDAZOL 1.000 MG COMPRIMIDO', 'SERTRALINA, CLORIDRATO 50 MG COMPRIMIDO', 'SIMETICONA 75 MG/ML SOLUÇÃO ORAL FRASCO 15 ML', 'SIMETICONA 75 MG/ML SUSPENSÃO ORAL FRASCO 10 ML', 'SINVASTATINA 20 MG COMPRIMIDO', 'SULFADIAZINA DE PRATA 1 % CREME BISNAGA 30 G', 'SULFAMETOXAZOL + TRIMETOPRIMA 40 + 8 MG/ML SUSPENSÃO ORAL FRASCO 100 ML', 'SULFAMETOXAZOL + TRIMETOPRIMA 400 + 80 MG COMPRIMIDO', 'SULFATO FERROSO (25 MG/ML DE FERRO ELEMENTAR) 125 MG/ML SOLUÇÃO ORAL FRASCO 30 ML', 'SULFATO FERROSO (40 MG DE FERRO ELEMENTAR) 109 MG COMPRIMIDO', 'SUXAMETÔNIO, CLORETO 100 MG PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA', 'SUXAMETÔNIO, CLORETO 500 MG PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA', 'TENECTEPLASE 50 MG PÓ PARA SOLUÇÃO INJETÁVEL FRASCO- AMPOLA 10 ML', 'TERBUTALINA 0,5 MG/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'TETRACICLINA, CLORIDRATO + ANFOTERICINA B 25 + 12,5 MG/G CREME VAGINAL BISNAGA 45 G', 'TIAMINA, CLORIDRATO 300 MG COMPRIMIDO', 'TIMOLOL, MALEATO 0,5 % SOLUÇÃO OFTÁLMICA FRASCO 5 ML', 'TIORIDAZINA, CLORIDRATO 100 MG COMPRIMIDO', 'TIORIDAZINA, CLORIDRATO 50 MG COMPRIMIDO', 'TOBRAMICINA + DEXAMETASONA 3 + 1 MG/ML SOLUÇÃO OFTÁLMICA FRASCO 5 ML', 'TOBRAMICINA 0,3 % SOLUÇÃO OFTÁLMICA FRASCO 5 ML', 'TRAMADOL, CLORIDRATO 100 MG CÁPSULA DURA DE LIBERAÇÃO PROLONGADA', 'TRAMADOL, CLORIDRATO 100 MG/ML SOLUÇÃO ORAL FRASCO 10 ML', 'TRAMADOL, CLORIDRATO 50 MG CÁPSULA', 'TRIMETAZIDINA 35 MG COMPRIMIDO', 'VALSARTANA 160 MG COMPRIMIDO', 'VARFARINA SÓDICA 5 MG COMPRIMIDO', 'VASOPRESSINA 20 UI/ML SOLUÇÃO INJETÁVEL AMPOLA 1 ML', 'VENLAFAXINA, CLORIDRATO 75 MG CÁPSULA DURA DE LIBERAÇÃO PROLONGADA', 'VERAPAMIL, CLORIDRATO 80 MG COMPRIMIDO', 'VITAMINAS DO COMPLEXO B (B1, B2, B3, B5, B6) DRÁGEA', 'VITAMINAS DO COMPLEXO B (B1, B2, B3, B5, B6) SOLUÇÃO INJETÁVEL AMPOLA 2 ML'
];

// Mapeamento dos medicamentos para o formato do objeto desejado
const medicamentosFormatados = listaDePrincipiosAtivos.map(principioAtivoCompleto => {
  const { concentracao, formaFarmaceutica } = parseMedicamento(principioAtivoCompleto);
  const isControlado = isPsicotropico(principioAtivoCompleto);

  return {
    principioAtivo: principioAtivoCompleto,
    concentracao: concentracao,
    formaFarmaceutica: formaFarmaceutica,
    psicotropico: isControlado,
    quantidadeEstoque: 0,
    estoqueMinimo: 100,
  };
});

async function main() {
  console.log('Iniciando o seeding...');
  
  // Cria todos os registros de uma vez
  const result = await prisma.medicamento.createMany({
    data: medicamentosFormatados,
    skipDuplicates: true, // Ignora se já existir
  });

  console.log(`Seeding concluído. Foram criados ${result.count} medicamentos.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });